version: '3.9'
services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    ports:
      - '5432:5432'

    volumes:
      - data:/var/lib/postresql/data
      - ./create_database_table.sql:/docker-entrypoint-initdb.d/create_database_table.sql
  pg-admin:
    image: dpage/pgadmin4:7
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - '5050:5050'
volumes:
  data: